name: Release

on:
  release:
    types: [published]

env:
  PACKAGE_NAME: mono-ui

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.tag.outputs.version }}
      tag_name: ${{ github.event.release.tag_name }}
      archive_name: ${{ steps.archive.outputs.archive_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Get version from release tag
        id: tag
        run: |
          VERSION=${{ github.event.release.tag_name }}
          echo "version=${VERSION#v}" >> $GITHUB_OUTPUT

      - name: Update package.json version
        run: |
          jq '.version = "${{ steps.tag.outputs.version }}"' package.json > tmp.$$.json && mv tmp.$$.json package.json

      - name: Get package archive name
        id: archive
        run: |
          echo "archive_name=${{ env.PACKAGE_NAME }}-${{ steps.tag.outputs.version }}.zip" >> $GITHUB_OUTPUT

      - name: Update package.json URL for release
        run: |
          jq '.url = "https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/${{ steps.archive.outputs.archive_name }}"' package.json > tmp.$$.json && mv tmp.$$.json package.json
     
      - name: Create ZIP archive
        run: |
          zip -r ${{ steps.archive.outputs.archive_name }} . -x "*.git*" -x ".github/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-assets
          path: |
            ${{ steps.archive.outputs.archive_name }}
            package.json

  upload:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: release-assets

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ needs.build.outputs.archive_name }}
            package.json
